spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      mode: embedded
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
# xml 방식으로 사용할 때 xml 위치 지정
mybatis:
  configuration:
    map-underscore-to-camel-case: true

  # xml 위치 지정
  mapper-locations: /mapper/mapper.xml

  # 경로 지정
  type-aliases-package: com.example.springbootmybatis.user.model